Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<pk>', views.DirectorView.as_view(), name='detalle_director'),
    path('movie/<pk>', views.PeliculaView.as_view(), name='detalle_pelicula'),
]

Python/Ejercicios/12.Django/Ejercicio12.1/cine/cine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'))
]

Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=32, help_text='Escribe el nombre del género')

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=64, help_text='Escribe el título de la película')
    director = models.ForeignKey("Director", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=240, help_text='Resumen de la película')
    estreno = models.CharField(max_length=4, help_text='Año de estreno')
    genre = models.ManyToManyField(Genre)

    def __str__(self):
        return self.title


class Director(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_dead = models.DateField('Died', null=True, blank=True)


    def __str__(self):
        return '%s  %s' % (self.first_name, self.last_name)

Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/views.py
from django.views import generic
from . models import *

class IndexView(generic.ListView):
    template_name = 'peliculas/directores.html'
    model = Director

class DirectorView(generic.DetailView):
    template_name = 'peliculas/director.html'
    model = Director

class PeliculaView(generic.DetailView):
    template_name = 'peliculas/pelicula.html'
    model = Movie

Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/templates/peliculas/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'peliculas/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
        <h1>{% block header-title %}Directores{% endblock %}</h1>
    </header>
    <main>{% block content %}{% endblock %}</main>
</body>
</html>

Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/templates/peliculas/director.html
{% extends "peliculas/base.html" %}

{% block title %}Director - {{ director }}{% endblock %}

{% block header-title %}{{ director }}{% endblock %}

{% block content %}
<p>{{ director.date_of_birth}} - {{director.date_of_dead | default_if_none:""}}</p>
<h4>Peliculas</h4>
<table>
    <tr>
    {% for movie in director.movie_set.all %}
        <td onclick="window.location.href='/movie/{{movie.id}}'">
            <span class="nombre_pelicula">{{ movie }}</span>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay peliculas aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/templates/peliculas/directores.html
{% extends "peliculas/base.html" %}

{% block title %}Directores{% endblock %}


{% block content %}
<table>
    <tr>
    {% for director in object_list %}
        <td onclick="window.location.href='/{{director.id}}'">
            <span class="nombre_director">{{ director }}{% if director.date_of_dead %}&dagger;{% endif %}</span>
        </td>
        {% cycle '' '' '</tr><tr>' %}
    {% empty %}
        <td>No hay directores aún</td>
    {% endfor %}
    </tr>
</table>
{% endblock %}

Python/Ejercicios/12.Django/Ejercicio12.1/cine/catalog/templates/peliculas/pelicula.html
{% extends "peliculas/base.html" %}

{% block title %}Pelicula - {{ movie }}{% endblock %}

{% block header-title %}{{ movie }}{% endblock %}

{% block content %}
<p><b>Año: </b>{{ movie.estreno}}</p>
<h4>Sinopsis</h4>
<p>{{ movie.summary | linebreaks }}</p>
{% endblock %}